x-docker-data: &defaults
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 1
        max-size: 100m
---
services:
  sonarqube:
    <<: *defaults
    container_name: sonarqube
    image: docker.io/library/sonarqube:25.9.0.112764-community
    environment:
      TZ: ${TZ}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
      SONAR_JDBC_URL: ${SONAR_JDBC_URL}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-temp:/opt/sonarqube/temp
    depends_on:
      - sonarqube-postgres
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarqube.loadbalancer.server.port=9000
      - traefik.http.services.sonarqube.loadbalancer.server.scheme=http
      - traefik.http.routers.sonarqube.service=sonarqube
      - traefik.http.routers.sonarqube.rule=Host(`sonar.your-domain.com`)
      - traefik.http.routers.sonarqube.entrypoints=websecure
      - traefik.http.routers.sonarqube.tls=true
      - traefik.http.routers.sonarqube.tls.certresolver=cloudflare
    networks:
      - sonarqube-network
      - traefik-network

  sonarqube-postgres:
    <<: *defaults
    container_name: sonarqube-postgres
    image: docker.io/library/postgres:17.6
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "${POSTGRES_USER}"']
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - sonarqube-postgres:/var/lib/postgresql/data
    networks:
      - sonarqube-network

volumes:
  sonarqube-data:
    name: sonarqube-data
    external: true
  sonarqube-extensions:
    name: sonarqube-extensions
    external: true
  sonarqube-logs:
    name: sonarqube-logs
    external: true
  sonarqube-temp:
    name: sonarqube-temp
    external: true
  sonarqube-postgres:
    name: sonarqube-postgres
    external: true

networks:
  sonarqube-network:
    name: sonarqube-network
    external: true
  traefik-network:
    name: traefik-network
    external: true
